spring.application.name=gestion_retos

server.servlet.context-path=/system/api/v1

application.port=${PORT}

# Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional (to see SQL on console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true